### ISSUE TITLE
How do you open and connect this with stake.com?

### ISSUE THREAD

**Issue by DIJABOY** [poky1084/HiloBot-v3#2]

**Comment by rainbot-ch** [comment]
> 
seems you figured it then? ^^

**Comment by poky1084** [comment]
Launching the Hilo-v3.exe thats all, the mirrors of Stake site can be selected in the bot

**Comment by KG562** [comment]
> Launching the Hilo-v3.exe thats all, the mirrors of Stake site can be selected in the bot 

Planning on making any updates to the bot?

**Comment by DIJABOY** [comment]
Thanks guys

**Comment by poky1084** [comment]
@KG562 not soon

**Comment by Chap720** [comment]
why cant i launch the bot it keeps giving me errors about not being able to find the project location its very frustratiing
\
