### ISSUE TITLE
Current Source

### ISSUE THREAD

**Issue by Masegi** [poky1084/HiloBot-v3#4]
Hi,

I'm using current release version (3.1), and i would love to add some modifications.

But when I download and open the source I get some missing references.

For example this is missing:
this.resetBaseWinamountOf.ValueChanged += new System.EventHandler(this.resetBaseWinamountOf_ValueChanged);
this.ResetBaseLossamountCheck.CheckedChanged += new System.EventHandler(this.ResetBaseLossamountCheck_CheckedChanged);
this.resetBaseLossamountOf.ValueChanged += new System.EventHandler(this.resetBaseLossamountOf_ValueChanged);

I could link this, but actually what i'm missing is the auto card feature too.

So, basicly, where can I find current (3.1) source - cause links in release sections seems to be outdated.

**Comment by poky1084** [comment]
Yeah, i know the current source has warning or errors, i messed up when added a commit!
Hope that you can fix the missing code. I won't update the latest code, if you make edits try to fix them, thanks.
I don't have Visual Studio installed to update at this time. Thanks for reporting.

**Comment by poky1084** [comment]
> So, basicly, where can I find current (3.1) source - cause links in release sections seems to be outdated.

The current release is 3.1 is the latest source on the repo

**Comment by Masegi** [comment]
https://github.com/poky1084/HiloBot-v3/archive/926abeb71414c939a3122fc1871bacb69c793c0f.zip
Thanks, this link works and the source seems to be up to date, thanks for your work ;)

**Comment by poky1084** [comment]
@Masegi HEre is the changes since that release:
https://github.com/poky1084/HiloBot-v3/commits/master
